### ISSUE TITLE
Android / iOS problem when download model

### ISSUE THREAD

**Issue by andrewsmoc** [atteneder/glTFast#123]
When I export the application for Android and iOS, the 3D model is not downloaded in GLTF or GLB format. I tried with https or http protocol with no result.

**Comment by ThimoVBE** [comment]
Did you enable the specific shaders specified in the documentation of the repo?

**Comment by atteneder** [comment]
Sorry about the inconvenience.

I need more information in order to offer help:

- Can you download just the gltf/glb file via UnityWebRequest successfully?
- How exactly do you try to load the models?
- Does it work with other models (e.g. from [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models))
  - If yes: Can you provide the files that are not working?
- What version of glTFast are you using
- What version of Unity are you using

Thanks

**Comment by atteneder** [comment]
Please provide the information I asked for and re-open
