### ISSUE TITLE
Where did onLoadComplete go?

### ISSUE THREAD

**Issue by udvaritibor** [atteneder/glTFast#134]
Hi!

I've just updated glTFast, hoping that there will be an "onProgress" callback, but now onCompleted is missing as well.

Did I miss something or it has been removed? If yes, why?

Also an onProgress callback (regarding loading, not downloading) would be great, even if it's a crude estimation.

Cheers! :)

**Comment by Bersaelor** [comment]
I also updated recently, and gltFast is now using [async/await](https://john-tucker.medium.com/unity-leveling-up-with-async-await-tasks-2a7971df9c57).

You don't have to add to `gltfAsset.onLoadComplete += OnLoadingFinished;` anymore, you can just do

```c#
    async void loadGlTF() 
    {
       var success = await gltfAsset!.Load(filePath, null, deferAgent, null);
       OnLoadingFinished()
    }
```

**Comment by udvaritibor** [comment]
> ```cs
>     async void loadGlTF() 
>     {
>        var success = await gltfAsset.Load(filePath, null, deferAgent, null);
>        OnLoadingFinished();
>     }
> ```

Thanks! :)

**Comment by atteneder** [comment]
> Did I miss something or it has been removed? If yes, why?

Indeed, as @Bersaelor already explained. I decided to not keep the obsolete event, since the switch to async requires changes anyways.

Regarding loading progress: You're absolutely right, but I want to hold this one off a bit longer and figure out proper streaming first.

Feedback is always welcome, thanks!
