### ISSUE TITLE
Comparing Golden 3D Model and imported Model

### ISSUE THREAD

**Issue by waseemkhan1989** [atteneder/glTFast#150]
Hi,

Is there any script that can be used to tell whether the Glb model is imported correctly or not? In plants and mechanical Engineering industry, the 3D models have large assemblies and it is impossible to tell by just looking at it whether the 3D model is imported correctly. 

So, I need a script/tool which can tell whether the positions of transforms and vertices, textures etc. are imported correctly.

Any help in this regard?

**Comment by atteneder** [comment]
Hi,

not that I know of.

You can inspect manually by comparing the result visually to another reference glTF viewer (like the [glTF-Sample-Viewer](http://gltf.ux3d.io/); [source](https://github.com/KhronosGroup/glTF-Sample-Viewer)).

Programmatically one could write automated tests, that compare results of different glTF integrations for Unity, but I don't think this is time well spent (and it does not guarantee that it is error-free).

hth

**Comment by waseemkhan1989** [comment]
I checked the above viewer but it does not provide much stats about the model. The Microsoft 3D viewer provides stats about mesh data( triangles, vertices, UV Set 0 and 1, vertex colors, material IDs), texture data(there are many parameters), Animation data and scene data.

Do you think, if I compare with this tool then it would be enough to prove the accuracy of imported 3D Model?

Best,
Waseem Khan

**Comment by atteneder** [comment]
Of course there's also the [glTF-Validator](https://github.khronos.org/glTF-Validator/) to get more info about the structure of the glTF.

This request is very abstract and vague. May I ask why do you need this for in first place? Do you need to guarantee correctness or is it just curiosity? Do you have a specific problem?

glTFast's license explicitly states absence of any kind of warranties. That being said, everything specified in the glTF 2.0 specification (and extensions) that is listed as supported in the [features documentation](https://github.com/atteneder/glTFast/blob/main/Documentation%7E/features.md) should work and I will continue to provide support for that as good as possible.

**Comment by waseemkhan1989** [comment]
Thanks for your prompt reply. I am a student and doing my Master thesis. My supervisor is insisting on this point that how will he know that the model is imported correctly/accurately and there are no errors or differences from the original/Golden model. So, actually he wants some results that could be quantifiable(could be represented in some numbers/quantities). He does not have knowledge about 3D models and I am confused that how can I convince him that the imported model is accurate. But my another supervisor who has knowledge, suggest me to write a script or use some sdk to prove the accuracy of 3D model.

**Comment by atteneder** [comment]
I see.

Here's my take on this:

There's no such thing as 100% guarantee that software is bug-free. You can minimize the risk though, by writing tests that are run repeatedly. Those tests should cover all code and include all kinds of corner cases.

glTFast does come with tests

- Performance tests
- Graphical tests

Both of them check if a set of models are loaded without errors. The performance tests help detect performance regressions and the graphical tests make a render of the model and compare it with previous results. If the difference is greater than a certain threshold, the test fails.

It would be possible to add tests, that check the final positions of certain nodes. I just never planned to, since I don't receive many issue reports regarding this.

The Khronos group (creators of the glTF spec) is working on a [certification program](https://www.khronos.org/blog/3d-commerce-working-group-upcoming-real-time-asset-creation-guidelines-for-retail-and-e-commerce), that defines a set of test models and tests to further ensure conformance. I will investigate this once it is available.

More tests will be added down the road, but I usually write those either upfront right away (test drive development) or issue-driven :)

I hope this answers your and your supervisors questions
