### ISSUE TITLE
Question:: Theres a diffrence in how my model is viewed in editor and on Android using UnityGLTF and GLTFast?

### ISSUE THREAD

**Issue by ThimoVBE** [atteneder/glTFast#159]
![temp1](https://user-images.githubusercontent.com/54366515/112748234-c2cf8100-8fba-11eb-93b7-f2bc30e587e3.PNG)
![temp2](https://user-images.githubusercontent.com/54366515/112748235-c531db00-8fba-11eb-92dd-349b570cf4f4.PNG)

As you can see in the images, when I use the UnityGLTF package, my model looks more realistic. When I use the GLTFast package my model looks a lot lighter. Any idea what may have caused these differences? Or what I can do to make them equal?

Thanks in advance!

**Comment by atteneder** [comment]
Hi @ThimoVBE,

Not sure where the problem is, since UnityGLTF might have errors as well. I'd suggest you to get another, third "opinion": try to view it in Khronos' reference viewer, the [glTF-Sample-Viewer](https://gltf.ux3d.io) ([source](https://github.com/KhronosGroup/glTF-Sample-Viewer)) and compare it to that.

If it looks correct there, please provide a sample file and describe the expected result and how it deviates.

thanks!

**Comment by atteneder** [comment]
Please provide a sample file and re-open
