### ISSUE TITLE
Warning message for Animation.cs

### ISSUE THREAD

**Issue by De-Panther** [atteneder/glTFast#198]
Unity show this warning for https://github.com/atteneder/glTFast/blob/6764cf26b9bbee340ce94cac6367c8bfbc3c086b/Runtime/Scripts/Schema/Animation.cs
```
Script 'Animation' has the same name as built-in Unity component.
AddComponent and GetComponent will not work with this script.
```
![image](https://user-images.githubusercontent.com/4749703/122622813-92bbe980-d0a2-11eb-842b-5cd1d9b3acaf.png)

I guess renaming the script file would solve the warning

**Comment by De-Panther** [comment]
Got the same warning for Camera
![image](https://user-images.githubusercontent.com/4749703/122652080-7755ea80-d145-11eb-9780-96149ec6f137.png)
https://github.com/atteneder/glTFast/blob/a9e30e81f7ef6ac6f6d79fd68ff13d12b316a164/Runtime/Scripts/Schema/Camera.cs

**Comment by atteneder** [comment]
Hi @De-Panther ,

Thanks for reporting!

Strange, I think I got the warning (about `Animation`), but removed them by renaming it to `GltfAnimation`. Since the warnings don't show up for me (in the Editor at leats), can you tell me how to reproduce them?

- Unity version?
- glTFast version?
- Active build target / platform
- Do those errors appear at build time or in Editor in general?

Thanks

**Comment by De-Panther** [comment]
I guess it's a bug in Unity, as those are not even `MonoBehaviour` classes.

Unity 2020.3.11f1.
glTFast 4.0.1.
WebGL
They happen in Editor, after deleting the Library folder and opening Unity (so it's like a first load of the project)
