### ISSUE TITLE
Question: Is there a timeline for implementing Morph targets?

### ISSUE THREAD

**Issue by ghalexxxx** [atteneder/glTFast#199]
Thank you very much.

**Comment by atteneder** [comment]
Thanks for your interest,

Morph targets was never requested before (you're the first one), so they didn't get prioritized.

I'm optimistic to be looking into them soon, since it's one of the last glTF 2.0 core spec features missing (after 2+ UV support, which is already in the making).

Please subscribe to #8 to get updates.
