### ISSUE TITLE
Distorted CesiumMan walking animation

### ISSUE THREAD

**Issue by dhawalbanker** [atteneder/glTFast#201]
Hi.. I was going through the web demo, noticed CesiumMan walking animation is distorted near both the armpits. 

Demo link: https://gltf.pixel.engineer/
Content: https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/CesiumMan/glTF-Binary/CesiumMan.glb

**Comment by atteneder** [comment]
Hi @dhawalbanker ,

Thanks for reporting. Maybe it's a bone number limit in the quality settings? Is it the same in the Editor?

**Comment by dhawalbanker** [comment]
Thanks, @atteneder for the quick response. Yup, it's buggy in the editor as well.

**Comment by atteneder** [comment]
This is indeed a quality setting issue!

To avoid this artifact, go to `Project Settings` > `Quality` > `Other` > `Skin Weights`, make sure it is set to `4 Bones` or `Unlimited` for **every** Quality level you have. Note: this will have a performance impact, this it is limted on lower quality settings by default.

**Comment by atteneder** [comment]
Another note:

Another factor that might make artifacts worse is when joints are not sorted by weights. In that case I suspect it's possible that the most significant joint (with the highest weight) is not considered, since it's not in the first slot.

Not all joints are sorted in CesiumMan.gltf are sorted properly, but I tried sorting them and it didn't make much of a difference when it comes to the artifacts in the armpits.

**Comment by dhawalbanker** [comment]
Thanks @atteneder !
