### ISSUE TITLE
pbrMetallicRoughness is assigned in the schema when not assigned in the GLTF.

### ISSUE THREAD

**Issue by camnewnham** [atteneder/glTFast#228]
In the[ GLTF reference](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#reference-material), it states:

> When not specified, all the default values of pbrMetallicRoughness apply.

However, it's a little confusing that accessing the material in `GenerateMaterial()` `GLTFast.Schema.Material.pbrMetallicRoughness` is not null - since this should reflect the JSON accurately.

Perhaps a utility function (i.e. `GetDefaultPbrMetallicRoughness`) could be used instead and left to the user to implement?

**Comment by camnewnham** [comment]
Closing just due to how minor this issue is.

**Comment by atteneder** [comment]
Hi,

sorry for the late reply. You're right, this is the fault of JsonUtility, which does the parsing. When it finds a `material`, it'll create a `Schema.Material` object with default values on all properties. This means `pbrMetallicRoughness` will be set to `new PbrMetallicRoughness()`, essentially empty but not null.

This behavior causes many headaches I had to workaround. If there's an actual problem, I'll have to detect this case (via `FakeSchema` and nullify the invalid property (which will slow down parsing). Otherwise I'll leave it for now and hopefully solve this with a new JSON parsing solution.

Regards

**Comment by atteneder** [comment]
Funny, this parser misbehavior triggers #241, which is another, unrelated issue
