### ISSUE TITLE
Multiple errors in exported GLTF file

### ISSUE THREAD

**Issue by cpetry** [atteneder/glTFast#276]
**Describe the bug**
Exported via script some basic meshes
Using the Visual Studio Code GLTF plugin I got several errors.
Also I cannot open the file with Windows 3D Viewer, Blender or any other GLTF viewer.

**Files**
[New site.zip](https://github.com/atteneder/glTFast/files/7519729/New.site.zip)

**To Reproduce**
1. Open the GLTF file with Visual Studio with the glTF Tools extension
2. See red errors

**Desktop (please complete the following information):**
 - Unity 2021.1.28f1 glTFast 4.4.6
 - Built-in renderpipeline
 - Windows
 
additionally (if significant for the bug):
- Declared minimum value for this component (0.00009989738464355469) does not match actual minimum (0.00009999999747378752).glTF Validator(ACCESSOR_MIN_MISMATCH)
- Accessor element at index 35 is NaN.glTF Validator(ACCESSOR_INVALID_FLOAT)
- Entity cannot be empty.glTF Validator(EMPTY_ENTITY)
- Vector3 at accessor indices 0..2 is not of unit length: 0.glTF Validator(ACCESSOR_VECTOR3_NON_UNIT)

**Comment by atteneder** [comment]
Hi @cpetry,

Thanks for the report. In case of `.gltf` files, you also need to attach all external files. That means the buffer file (usually same name as the gltf file with a `.bin` extension) and textures (there seem to be none for your file).

On top of that it would be more helpful to have the original assets to test the export on. Can you provide those? (Select them in the project view and go menu > assets > export package).

- The difference in min-max values is a very small one due to precision loss in Unity. The solution will be to iterate buffers for actual min-max values (it's on my list)
- The empty `images` prop looks like a bug.
- To inspect the other errors, I need the missing files or better, the assets.

thanks!

**Comment by cpetry** [comment]
Ah sorry for this. The *.bin should have been inside already.
Here the gltf + bin.
[New site.zip](https://github.com/atteneder/glTFast/files/7519729/New.site.zip)

**Comment by atteneder** [comment]
@cpetry Alright, thanks!

Currently export only works with png/jpeg that are simply copied over. Maybe you used another type (support for those is to be added soon).

I don't know what to make of the invalid buffer values. Again, the original assets would help a lot here.

**Comment by cpetry** [comment]
I can't export the assets as they get created via numerous scripts in runtime.
Also the materials are created/setup in runtime (Standard built-in shader)
So there exist no direct jgp/png (at least not as an asset)

**Comment by atteneder** [comment]
Ah, that explains why images are missing. Runtime export is not tested atm, but it'll get added over time.

**Comment by atteneder** [comment]
Not sure about the invalid values though. Chances are, they are invalid in the mesh already, but it's impossible to tell. Let me know if you have steps to reproduce this for me.

**Comment by atteneder** [comment]
@cpetry Please try out the latest version 4.6.0. It received many improvements. In case you still have trouble, provide reproduction steps and re-open.
Thanks
