### ISSUE TITLE
Gltf Exporter Loss Model Material

### ISSUE THREAD

**Issue by jhx-zc** [atteneder/glTFast#300]
**Describe the bug**
Gltf Exporter Loss Model Material.

> Here is my demo job.

**Files**
In unity,with model material
![unity_demo](https://user-images.githubusercontent.com/52167297/148971406-f612a5a3-c044-4f21-9a9a-f3d857813350.png)

After exported,without model material
![without_demo](https://user-images.githubusercontent.com/52167297/148971761-23f16b5d-fca9-44b2-a58b-12dbe2631ca2.png)

Exported files:
[demo.zip](https://github.com/atteneder/glTFast/files/7847699/demo.zip)

**Desktop (please complete the following information):**
 - glTFast version:4.4.9
 - Unity Editor version [2021.2.1f1]
 - Render Pipeline and version [e.g. Universal Render Pipeline 12.0]
 - Platform: [Windows]

**Additional context**
What can i do if i need export with material?

Thanks for your help

**Comment by atteneder** [comment]
@jhx-zc Thanks for the report and congrats on issue nr. 300  🥳

Since export is still experimental, likely the type of material/shader you're using does not work yet.

Could you specify which shader your model uses? Your RP is Universal 12.0, correct?

If you can, please export the original model as a package (via menu `Assets -> Export Package`).

**Comment by jhx-zc** [comment]
> Could you specify which shader your model uses? Your RP is Universal 12.0, correct?

Oh,sorry.
I can not specify the shader,but the model which i exported can be find at unity asset store.Here is the [link](https://assetstore.unity.com/packages/3d/environments/industrial/rpg-fps-game-assets-for-pc-mobile-industrial-set-v2-0-86679).

It is a free env asset.I ues it for GLTF file exporter test.

**Comment by jhx-zc** [comment]
And,today i consult with an UI designer.He told me that the problem is the exporter.

**Comment by atteneder** [comment]
@jhx-zc So, I'm having a look at this right now, but before I give any technical feedback:

This asset is distributed under the [Standard Unity Asset Store EULA](https://unity3d.com/legal/as_terms). Whatever you intend to do with exported glTFs, make sure you comply with the license.

The author also states that you've got to make a donation in order to use it commercially, so make sure you comply.

That being said, here's what it looks like exporting with current main:
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/2593014/155101482-6c7770d9-57d0-4682-873f-c69a72b682e5.png">

There seems to be a UV problem, but it's getting closer.

Did you also convert the Built-In materials (using the Mobile shader) to URP ones (Simple Lit) ?

Simple Lit is not tested  (only tested Lit so far), so I'm going to leave this issue open until I did.

**Comment by atteneder** [comment]
Seems to be resolved.
