### ISSUE TITLE
Primitive Mode TRIANGLE_STRIP and TRIANGLE_FAN

### ISSUE THREAD

**Issue by atteneder** [atteneder/glTFast#316]
The following [glTF primitive modes](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#_mesh_primitive_mode) are not implemented:

-`TRIANGLE_STRIP`
-`TRIANGLE_FAN`

Unity does not support those out of the box, so glTFast needs to generate indices (similar to how it creates them for missing indices on `TRIANGLES` mode primitives).

Unfortunately I've never encountered such a glTF file, so we'd have to find or create one first.

**Comment by Hexer611** [comment]
Chronos group has a glTF asset generator which should be useful as an example to implement these primitive modes.
Link: https://github.khronos.org/glTF-Asset-Generator/Output/Positive/Mesh_PrimitiveMode/

I would like to contribute to this project. Since this issue is tagged with "good first issue" I believe this is a good point to try it :D

Out of context note: The link to "code of conduct" in "https://github.com/atteneder/glTFast/blob/openupm/CONTRIBUTING.md" doesn't work, I could send a PR to fix that if possible :D

**Comment by atteneder** [comment]
@Hexer611 Thanks for going ahead and submitting PRs.

Regarding the incorrect linke: Sure, go ahead! Targetting the Unity fork is the way to go.

I'll look at your PR in 1-2 weeks.

Keep it up!

**Comment by atteneder** [comment]
This feature has been released with [glTFast 6.8.0](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.9/changelog/CHANGELOG.html#680---2024-09-05).

Thanks!
