### ISSUE TITLE
Embed buffers could not be imported successfully。

### ISSUE THREAD

**Issue by Phlicess** [atteneder/glTFast#336]
Hello，My GLTF file is embed buffers，use
`string sgltf = "https://a.amap.com/jsapi/static/HD_road/0726/mock/models/circle.gltf";`
`var gltf = gameObject.AddComponent<GLTFast.GltfAsset>();`
`gltf.url = sgltf;`
Failed to import，no error message。Has warn "logger?.Warning(LogCode.EmbedSlow);"
`JSON embed buffers are slow! consider using glTF binary`
What should I do?

**Comment by atteneder** [comment]
@Phlicess Thanks for reporting.

This glTF file contains one scene, but does not have a [default scene](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#_gltf_scene). glTFast will, by default, not instantiate this scene in that case according to the [specification](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#scenes-overview):

> An additional root-level property, scene (note singular), identifies which of the scenes in the array SHOULD be displayed at load time. When scene is undefined, client implementations MAY delay rendering until a particular scene is requested.

There are ways to solve this:

- Modify your glTF, so that is has the correct default `scene` property set
- Set the `GltfAsset`'s sceneId to `0` to load the first scene (see example below)
- Implement your own variant of `GltfAsset` that loads the first (or any other or all) scene(s).

```csharp
string sgltf = "https://a.amap.com/jsapi/static/HD_road/0726/mock/models/circle.gltf";
var gltf = gameObject.AddComponent<GLTFast.GltfAsset>();
gltf.url = sgltf;
gltf.sceneId = 0;
```

I can see that this is confusing.

hth

P.S.: The warning about embed buffer is unrelated.

**Comment by Phlicess** [comment]
> @Phlicess Thanks for reporting.
> 
> This glTF file contains one scene, but does not have a [default scene](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#_gltf_scene). glTFast will, by default, not instantiate this scene in that case according to the [specification](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#scenes-overview):
> 
> > An additional root-level property, scene (note singular), identifies which of the scenes in the array SHOULD be displayed at load time. When scene is undefined, client implementations MAY delay rendering until a particular scene is requested.
> 
> There are ways to solve this:
> 
> * Modify your glTF, so that is has the correct default `scene` property set
> * Set the `GltfAsset`'s sceneId to `0` to load the first scene (see example below)
> * Implement your own variant of `GltfAsset` that loads the first (or any other or all) scene(s).
> 
> ```cs
> string sgltf = "https://a.amap.com/jsapi/static/HD_road/0726/mock/models/circle.gltf";
> var gltf = gameObject.AddComponent<GLTFast.GltfAsset>();
> gltf.url = sgltf;
> gltf.sceneId = 0;
> ```
> 
> I can see that this is confusing.
> 
> hth
> 
> P.S.: The warning about embed buffer is unrelated.

Nice！Thx！
