### ISSUE TITLE
JSON parse error : Missing a name for object number

### ISSUE THREAD

**Issue by CorentinDel** [atteneder/glTFast#374]
**Describe the bug**
Reimport an exported gtlf file trigger a json error.

**Files**
[Scene_exporter_runtime.zip](https://github.com/atteneder/glTFast/files/8381543/Scene_exporter_runtime.zip)

For more informations : it's 4 cube inside an empty scene

**To Reproduce**
1. Click on `file -> Export Scene -> glTF (.gltf)`
2. Save your export anywhere (i did inside a folder on my desktop)
3. Wait the export is complete
4. Reimport the export inside the project
5. JsonUtility trigger an error

**Expected behavior**
The reimport is done correctly and i can use my export inside my scene

**Screenshots**
[Screenshot of the scene i exported and the error i got when reimport.](https://imgur.com/a/7HWB5Mk)

**Desktop (please complete the following information):**
 - glTFast version : 4.6.0
 - Unity Editor version : 2020.3.27f1
 - Render Pipeline and version : Universal Render Pipeline 10.8.1
 - Platform: Editor

**Comment by Daniel4144** [comment]
Hi, I assume you were using the Unity default cubes; I experienced the same with these (same import error). The problem seems to be the default material/shader. When I create and assign a material with a different shader, exporting and importing works for me.
So it does not work with the shader  'Standard', but it does with the 'Standard (Specular setup)'.
I have only tested with the builtin renderpipline, but maybe try another shader to check if that works.

**Comment by atteneder** [comment]
@CorentinDel  Thanks for reporting!

Do you, by chance, use a system that's configured to use a coma (`,`) as decimal point? If yes, this is another instance of [this issue](https://github.com/atteneder/glTFast/issues/335). I'll have a look!

**Comment by atteneder** [comment]
@CorentinDel Actually, this should already be fixed in the current `main` branch and thus with the next release. Can you, by chance, test the current development  version?

**Comment by atteneder** [comment]
Assuming it's fixed. Please re-open if that's not the case.
