### ISSUE TITLE
Texture y-flips with KHR_texture_basisu extension on gltfast URP

### ISSUE THREAD

**Issue by wonkee-kim** [atteneder/glTFast#390]
**Describe the bug**
When glTFast-URP brings a model that uses `KHR_texture_basisu`, the texture appears y-flipped. I am using version 4.4.6.
It was okay with Built-in render pipeline.
The texture seems coming right(same with Built-In), but some of URP shaders flip it, and others don't as their baseColorTexture_ST is different.

[Not-Flipped]
glTF-metallic-Opaque
glTF-unlit-Blend
glTF-unlit-Blend-double
glTF-unlit-opaque
glTF-unlit-opaque-double

[Flipped]
glTF-metallic-Blend
glTF-metallic-Blend-double
glTF-metallic-Opaque-double
glTF-metallic-Premultiply
glTF-metallic-Premultiply-double

**Files**
[Archive 2.zip](https://github.com/atteneder/glTFast/files/8592172/Archive.2.zip)
Two glb models - one is okay, and another y-flips. The problem one uses `KHS_texture_basisu`.

**To Reproduce**
1. Upload both glb files attached.
2. See the face texture appears okay.

**Expected behavior**
It shouldn't be flipped.

**Screenshots**
![Screen Shot 2022-04-29 at 12 10 45 PM](https://user-images.githubusercontent.com/830808/165982756-b44cc2fd-5837-4a6b-93d3-1e23fce10f9a.jpg)

![Screen Shot 2022-04-29 at 11 53 08 AM](https://user-images.githubusercontent.com/830808/165982343-8b410181-cb84-4728-bebf-163542d45e8b.jpg)

**Desktop (please complete the following information):**
 - glTFast version: 4.6.0
 - Unity Editor version: 2020.3.19f
 - Universal Render Pipeline 10.6.0
 - Platform: All (Editor, webgl, Android, iOS]
 
additionally (if significant for the bug):
- All devices

**Comment by atteneder** [comment]
@wonkee-kim Thanks for the report.

I cannot reproduce on

- Unity 2021.3.1f1 or 2020.3.33.f1 on macOS/Vulkan
- glTFast 4.7.0
- URP 12.1.6/10.8.1 nor BiRP
- KtxUnity 2.1.2/1.3.2

Note: It is expected that the texture is flipped upside-down in the inspector. Unity has a different texture orientation than KTX. It should be correct on the model though, since the texture tiling is transformed to counter balance.

Maybe try updating your packages to the ones I used above and test again.

**Comment by wonkee-kim** [comment]
oh sorry, I was using 4.4.6 version and just upgraded 4.7.0 and it's fixed!
Thank you so much for your effort.
