### ISSUE TITLE
Texture rotation yields slightly incorrect results

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/glTFast#413]
**Describe the bug**
Seems texture rotation is _nearly_ but not quite correct

*To Reproduce**
1. Download https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureTransformTest
2. Put into Unity to be imported by glTFast with URP 12.x
3. Note that there's a slight difference between the reference and the result:

**Reference**
![image](https://user-images.githubusercontent.com/2693840/171942501-bf45b309-8a39-4b29-8e63-370d9d89ffd1.png)

**Result**
![image](https://user-images.githubusercontent.com/2693840/171942546-e5211296-a778-4eba-b98f-90e1922015b4.png)

(middle looks ok, left is rotated around the wrong point and doesn't point exact, right doesn't point exact)

The test asset is unfortunately not very suited for testing rotation, as there's many combinations of slightly wrong transform orders etc. that yield "ok looking" results...

**Desktop (please complete the following information):**
 - glTFast version 4.8
 - Unity Editor version 2021.3
 - Render Pipeline URP 12.x
 - Platform Editor

**Comment by atteneder** [comment]
@hybridherbst Thanks a lot for reporting!

A multiplication of the horizontal offset with the cosine of the rotation was done twice by accident. This is actually a lot worse if the rotation is further from zero (or the offset is a higher value).

When I first read the texture transform extension spec I thought the rotation seems expendable, since I never or hardly came across assets that require it (also Unity's Standard and Lit shaders don't support it either). The fact that nobody, exept you, reported this blatant bug kind of proves my initial stance 😄 

Fix release coming this week!

**Comment by atteneder** [comment]
fixed in [4.8.5](https://github.com/atteneder/glTFast/releases/tag/v4.8.5)
