### ISSUE TITLE
Emission doesn't seem to work

### ISSUE THREAD

**Issue by Kinerius** [atteneder/glTFast#459]
**Steps To Reproduce**

- Create a new project by selecting `3D Sample Scene (URP)`
- Create 2 spheres
- Create 2 materials and assign them to the spheres
- Set one material to `UniversalRenderPipeline/Lit` and the other to `glTF-pbrMetallicRoughness-Opaque`
- Set the emissive color to something bright

I've also added some textures just to test if that was needed.

**Screenshots**
![image](https://user-images.githubusercontent.com/7646450/188215002-9714e119-9ab8-4ba1-b5f1-fa9ccf83d385.png)

**Desktop**
 - glTFast version: latest
 - Unity Editor version: 2020.3.34f1
 - Render Pipeline and version: URP latest
 - Platform: Windows
 
---
 **Additional info**

 I noticed that something was off when importing some GLTFs on a test branch at the project I'm working with and found out that the emissions weren't working as expected. So I did this little test to see if it was our project that had that problem.

**Comment by atteneder** [comment]
Hi @Kinerius ,
Thanks for reporting!

The problem is probably, that the `_EMISSION` keyword is not enabled on the glTF shader material.

The (URP) Lit material editor (inspector) is great, because it automatically enables or disables shader keywords required. The glTF shaders on the other hand are not primarily designed or optimized to be edited by hand, thus atm you'd have to do those things yourself.

A proper long-term solution would be custom material editors with streamlined UI and all glTF material feature settings.

I've opened a [feature issue](https://github.com/atteneder/glTFast/issues/460) (#460  for that. Consider giving your feedback/inputs and subscribing to it.

hth
