### ISSUE TITLE
Option for self-shadowing on Unlit materials?

### ISSUE THREAD

**Issue by ROBYER1** [atteneder/glTFast#465]
Allow glTF-unlit to cast shadows on itself on the material and receive shadows from other objects casting shadow (including other unlit shadow casters)

**Describe alternatives you've considered**
Custom shader overriding the glTF-Unlit shader included in the package, or duplicate the package locally and mess with it

Something like this:
![image](https://user-images.githubusercontent.com/10745594/189150970-8e8b4755-364b-48a9-8ed7-ceb6b41919ce.png)

**Comment by ROBYER1** [comment]
This is more of a hacky workaround, I managed to sort of do this myself with this package, it might be useful to you or other users trying this. Technically its not fully unlit of course as turning off a directional light will make the model black/very dark due to a full shadow covering it/no light but it won't respond to point lights etc so will behave as unlit for as long as you have a Directional light in the scene.

![Image20220908165237](https://user-images.githubusercontent.com/10745594/189168387-8d2d252b-dd51-4451-8508-0f9621765148.png)


[UnlitReceiveSendShadows.zip](https://github.com/atteneder/glTFast/files/9528444/UnlitReceiveSendShadows.zip)

**Comment by atteneder** [comment]
Hi @ROBYER1 ,

Unfortunately the glTF spec does not say anything about shadows/shadowing, so it's unclear to decide what's correct.

I'd argue in most cases it is desirable to not have unlit materials cast or receive shadows.

Also I'm curious, what should the shadow color look like? How is it calculated? I'm asking since this goes against the concept of unlit.

I don't see this as a core feature to be implemented. If you do want to have a custom shadow effect, I'd recommend creating your own shader and `IMaterialGenerator`. A good starting point is to fork the existing ones.
