### ISSUE TITLE
Emission color change doesn't work at runtime if emission texture was not set in glb.

### ISSUE THREAD

**Issue by artyomabgaryan** [atteneder/glTFast#549]
**Describe the bug**
Emission parameter doesn't work at runtime if emission texture was not set in glb.

**To Reproduce**
1. Create to objects on blender` one with emission texture set and other without texture
2. Load glb
3. Try to change emission color on object without texture
**Expected behavior**
Changing at runtime(in editor) emission color will not change

**Comment by atteneder** [comment]
Hi @artyomabgaryan ,

You need to enable the shader keyword `_EMISSIVE` on included glTF shaders in order to get emission working.

The importer does that for you in case the emissive color is something else than black or (as in your case) an emissive texture is assigned.

Now, ideally glTFast would have custom shader inspectors that handle enabling/disabling shader keywords automatically. This is covered in #460, but there's currently no plans to start implementing those (help is welcome).

hth

**Comment by artyomabgaryan** [comment]
@atteneder 

![image-8z49ky6kg7r7mjjo15yih6ytgc](https://user-images.githubusercontent.com/73118592/233045981-f8d3c307-e6c8-48ad-b4d6-873924006241.png)

 even if I enable that keyword changing the emission color at runtime gives 0 result


https://user-images.githubusercontent.com/73118592/233046268-e26677c3-f5fe-42e3-84d7-d473fd4e86ab.mp4
