### ISSUE TITLE
Shared accessor are loaded multiple times - Out of Memory

### ISSUE THREAD

**Issue by julienduroure** [atteneder/glTFast#57]
Hello,
I am one of the maintainer of the Blender glTF importer/exporter (see https://github.com/KhronosGroup/glTF-Blender-IO).
I am also a 3D engineer at Airbus Defence & Space, and we are currently testing glTFast to import glb file in Unity at runtime. You are doing a great job!

We are currently facing a bug using shared accessor.
Here is the case:
* A mesh with multiple primitives
* A big accessor with all position of the mesh
* A big accessor with all normals of the mesh
* A big accessor with all UVs of the mesh
* Each primitive has, of course, its own indice accessor, linking to some position/ normals/UVs of the big accessor.

Example:

![example](https://user-images.githubusercontent.com/1696020/73072579-a49d5b00-3eb5-11ea-96d7-a5565149ae0d.png)

Seems that in your code, the big accessor (0, 1 and 2 in my example), are loaded one time by primitive. We have some models, not so big (glb is 3.7Mo, 62000 vertices), but with many primitives (more than 5000). Because of the loading of 62000 data for each primitive, we run out of memory (32Go), where these accessors should be decoded only once for all the primitives.

I can't unfortunally share the model with you (even in private), but I create a simple test case with shared accessor. This is only a cube with 6 primitives, so no really some memory issuewith this file, but it will let you test understand / test what should be done to fix this issue.

[test_cube.zip](https://github.com/atteneder/glTFast/files/4108636/test_cube.zip)

Thanks a lot!

**Comment by atteneder** [comment]
Hi Julien,

thanks a lot for this text book example of a bug report :)

I noticed this misconception in glTFast when I was investigating #52 

My plan is to release my current work (fix normal mapping and KHR_mesh_quantization support) and then change glTFast to load per-accessors instead of per-primitive. But to make this easier, I'd like to refactor the core  (`GltFast.cs`) a bit, since it's quite confusing.

Your use-case sounds very interesting! I'll try to look at it the next 2 weeks.

Good to hear you like glTFast otherwise.

Thanks,
andi

**Comment by julienduroure** [comment]
Thanks for the feedback.
Don't hesitate to poke me as soon as you have a testable branch, if you want me to test it on the big (non shareable) file.

**Comment by atteneder** [comment]
good news: I have a refactored branch (not pushed yet) that does convert buffers into Unity types (position Vector3[] etc.) once per accessor (and not per primitive) anymore.

bad news: the vertex attribute buffers (positions,normals,uvs,etc.) still get duplicated due to limitation in Unity's Mesh API. To double check this, I asked this in the Unity forums:
<https://forum.unity.com/threads/feedback-wanted-mesh-scripting-api-improvements.684670/page-2#post-5433048>

If this limitation turns out to be unavoidable, I see two alternative solutions:

1. Create glTFs with that limitation in mind and avoid shared accessors. May be tricky, if the used glTF exporter does not support a setting for it.

2. Fix it by detecting and splitting shared vertex buffers at run-time. Not ideal, but probably the only way to get huge files like that to work.

For now I'll do a bit more refactoring,research and look at the new Mesh API that came with 2019.3.

**Comment by atteneder** [comment]
Hi Julien,

after another look I figured out that the test cube you provided actually does not suffer from accessors being used across meshes. They are just used across primitives within one mesh. So basically my last post doesn't apply to the cube and hopefully not to your real data as well.

That being said, I have a branch ready for testing, that improves in two ways:
- buffers are not retrieved multiple times (once instead 6 times for the cube)
- only one unity mesh is created per gltf mesh (if all its primitives have identical attributes)

It should be a lot more efficient. Go ahead and test it, please:
<https://github.com/atteneder/glTFast/tree/refactor_accessor_loading>

feedback is very welcome. I'll release it soonish.
thanks!

**Comment by julienduroure** [comment]
Hello,
Thanks for this update. I will test it in the following days.
You're right, in my cases, accessors are shared by multiple primitives, but inside a same mesh. I never find a test case where accessors are shared between multiple meshes.

**Comment by atteneder** [comment]
Me neither. That's why I decided to not pay attention to those cases and focus on optimizing your case.

Also: Next step is to optimize the Jobs/Threads and utilize Burst/Unity.Math. First tests are promising so expect speed improvements on your big scenes in the coming days/weeks.

**Comment by atteneder** [comment]
fyi: was merged+released already.

**Comment by julienduroure** [comment]
Thanks a lot!
We are a bit late in our dev here, tests on our production data is not done yet.
Hope we will be able to perform tests next week

**Comment by atteneder** [comment]
I think it's safe to close it now. Feel free to re-open if you still encounter the problem.
