### ISSUE TITLE
Animation loop control

### ISSUE THREAD

**Issue by MasterZ0** [atteneder/glTFast#572]
I'm trying to download and add animation at runtime. But it's impossible to set the animation to Loop via code. Maybe you could add way to do this through the library to give better Unity compatibility.

![image](https://user-images.githubusercontent.com/64444068/218008526-47c6750f-5a0d-406c-92c5-e2d534e2bfac.png)

**Comment by atteneder** [comment]
Hi,

setting the `wrapMode` to Loop shouldn't be required as this is done [by default](https://github.com/Unity-Technologies/com.unity.cloud.gltfast/blob/64f3257d9354fd61e8a9232690648cc2f1d4b941/Runtime/Scripts/GltfImport.cs#L2264).

I'm going to assume that you're using the Mecanim animation method and use a custom animation controller. I think the problem is within that controller of yours.

If I'm mistaken, feel free to re-open the issue and provide a project that reproduces the problem.

Thanks.
