### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by edgarrodrigosantos** [atteneder/glTFast#58]
Hi,

The project doesn't compile after downloading dependencies for UWP build target with the following error:
"Library\PackageCache\com.atteneder.draco@85765a855cad1a4848678a894b17213e27df9ef6\Runtime\Scripts\DracoMeshLoader.cs(69,14): error CS0103: The name 'DRACODEC_UNITY_LIB' does not exist in the current context"

Is there any way around this?

Thank you

**Comment by atteneder** [comment]
Hi,

I never tried this platform, so some things are not defined properly. try this:

open `DracoMeshLoader.cs` (found inside the DracoUnity package)

and change this (line 30):
```csharp
	#if UNITY_EDITOR_OSX || UNITY_WEBGL || UNITY_IOS
        public const string DRACODEC_UNITY_LIB = "__Internal";
    #elif UNITY_ANDROID || UNITY_STANDALONE
        public const string DRACODEC_UNITY_LIB = "dracodec_unity";
    #endif
```

to:
```csharp
	#if UNITY_EDITOR_OSX || UNITY_WEBGL || UNITY_IOS
        public const string DRACODEC_UNITY_LIB = "__Internal";
    #elif UNITY_ANDROID || UNITY_STANDALONE || UNITY_WSA || UNITY_EDITOR
        public const string DRACODEC_UNITY_LIB = "dracodec_unity";
    #endif
```

It may be, that UWP still needs a different binary of the Draco library.

please let me know if it works.

**Comment by atteneder** [comment]
The editor should work though, but the final build might still not.

**Comment by edgar-rodrigo-santos** [comment]
It works (both Editor and UWP runtime on Hololens).

The rendering is great (probably the best I've seen from gltf loaders) but it is too much for us (we want to keep the framerate very high with the fastest shaders possible even sacrificing quality).

In terms of shaders, the ideal scenario would be to support the MRTK library standard shader (which is a more efficient version of the Unity Standard shader).
(https://github.com/microsoft/MixedRealityToolkit-Unity)
One of the advantages being that it looks like it can take advantage of the Universal Rendering Pipeline (previously, Lightweight Rendering Pipeline).

In alternative, is it possible to change something in your code to support Unity Standard Shader? Since we already "map" the Unity Standard Shader to MRTK's, it would be much faster for us to use...

Also, the API assumes all the gltf files (e.g. bin, png) are in the same url which is not the case for us (we did a fork and maybe we can contribute with that).

On a final note, there's memory leaks on Hololens but we're pretty sure it's not your fault but rather a nasty unity bug described here:
https://issuetracker.unity3d.com/issues/windows-memory-leak-on-net-4-dot-x-and-x86-builds?_ga=2.173610403.121171497.1581087069-923281491.1500369376

Thanks

**Comment by atteneder** [comment]
> It works (both Editor and UWP runtime on Hololens).
> 
Great to hear! I'll include this fix in the next release then.

> The rendering is great (probably the best I've seen from gltf loaders) but it is too much for us (we want to keep the framerate very high with the fastest shaders possible even sacrificing quality).
> 
> In terms of shaders, the ideal scenario would be to support the MRTK library standard shader (which is a more efficient version of the Unity Standard shader).
> (https://github.com/microsoft/MixedRealityToolkit-Unity)
> One of the advantages being that it looks like it can take advantage of the Universal Rendering Pipeline (previously, Lightweight Rendering Pipeline).
> 
> In alternative, is it possible to change something in your code to support Unity Standard Shader? Since we already "map" the Unity Standard Shader to MRTK's, it would be much faster for us to use...
> 
glTFast started out using Unity's standard shader. I eventually forked it into custom shaders in order to provide all features the glTF materials offer (double-sided, vertex colors, occlusion/roughness/metallnes textures, texture transforms with rotation). So I don't intend to go back here.

But, I see that there's a need for different material creation / shader usage. For that reason I abstracted the `DefaultMaterialGenerator` behind an interface: `IMaterialGenerator`. You should be able to write your own, custom one and pass it to the Gltfast instance.
Admitted, at the moment it's not used and might change somewhat, but I plan to use it once I tackle Unity's URP support.

> Also, the API assumes all the gltf files (e.g. bin, png) are in the same url which is not the case for us (we did a fork and maybe we can contribute with that).
> 
Not sure what you mean exactly. You can provide arbitrary URLs, but URIs within the glTF file will be considered relative to the original gltf/glb file, if that's what you mean.
Anyhow, if you have a point with your changes and contribute them, I'll gladly take a look and do PR reviews.

> On a final note, there's memory leaks on Hololens but we're pretty sure it's not your fault but rather a nasty unity bug described here:
> https://issuetracker.unity3d.com/issues/windows-memory-leak-on-net-4-dot-x-and-x86-builds?_ga=2.173610403.121171497.1581087069-923281491.1500369376
> 
Alright. If the leaks happen to be suspicious towards glTFast / KtxUnity or DracoUnity, let me know so I can test it.

> Thanks

happy to help and get feedback

**Comment by atteneder** [comment]
Both DracoUnity and KtxUnity now have this change applied and should work on UWP.
