### ISSUE TITLE
Compile Error occurs when applying "GLTFAST_SAFE" Script Define Symbols

### ISSUE THREAD

**Issue by jeoungjukim** [atteneder/glTFast#656]
**Describe the bug**
I have been loading gltf models using GLTFast, and have enabled Safe Mode according to the ProjectSetup guide. (Otherwise joint normalization issues will occur). 
However, after glTFast v6.0.0, if Safe Mode is enabled, the Compile Error occurs
This is a serious problem and can hinder development progress. Please fix it quickly.

**To Reproduce**
1. Import glTFast v6.0.0 and higher into Unity project.
2. To enable Safe Mode, enter “GLTFAST_SAFE” in Script Define Symbols and apply.
3. Check the error message “The name ‘accessors’ does not exist in the current context” as a compile error.

**Expected behavior**
Safe Mode should work normally without compilation errors as in versions prior to glTFast v6.0.0.

**Screenshots**
<center>
<img src="https://d3unf4s5rp9dfh.cloudfront.net/AREmoji_doc/GLTFastBug1.png"  width="900"/>
<img src="https://d3unf4s5rp9dfh.cloudfront.net/AREmoji_doc/GLTFastBug2.png"  width="900"/>
</center>

**Desktop (please complete the following information):**
 - glTFast version: v6.0.0 and higher
 - Unity Editor version: 2022.2.2f1
 - Render Pipeline and version: Built In
 - Platform: Window
 
additionally (if significant for the bug):

 - Device: Galaxy
 - OS: n/a 
 - For WebGL: n/a

**Comment by vrenken** [comment]
Hi,

I don't have time to create a fully fledged fix for this, but we just noticed this as well. 
Nevertheless still want to provide the information below - Maybe it helps someone in the future:

The non-generic RootBase class has an uppercase abstract property called Accessors, whereas the generic Rootbase has a lowercase field called accessors. 
A fix should be as simple as at line 574 to 578 changing to access the Accessors property instead of the accessors field.

**Comment by atteneder** [comment]
This has been addressed in version [6.3.0](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.6/changelog/CHANGELOG.html#630---2024-03-27).

hth
