### ISSUE TITLE
Use MaterialPropertyBlock instead of  Material ,increase draw call 

### ISSUE THREAD

**Issue by veyvin** [atteneder/glTFast#66]
https://docs.unity3d.com/ScriptReference/MaterialPropertyBlock.html

**Comment by atteneder** [comment]
Hi veyin,

can you shed a bit of light onto what you suggest with this?

I assume it would be possible to save draw calls by finding materials of a glTF file that use an identical shader(variant), but have varying properties. You'd have to group those together, is that what you're implying?

**Comment by veyvin** [comment]
yep，i have a lot of models

![2020-04-13 173726](https://user-images.githubusercontent.com/6776758/79110677-89a00000-7dad-11ea-8c14-d057d6d42ff8.png)


![2020-04-13 173919](https://user-images.githubusercontent.com/6776758/79110803-ca981480-7dad-11ea-8c33-0d780f6dc83a.png)

**Comment by atteneder** [comment]
Interesting use case! Can you provide a sample file(s)?

I'll put it on the list of feature requests, but cannot make promises since this list is long.

In case you want to give it a try yourself, this is how I'd approach it:

Currently each Gltfast instance creates its own instance of DefaultMaterialGenerator (IMaterialGenerator), which creates the materials. The intention is, that alternative MaterialGenerators can be overriden/passed as parameter to change this behavior (For example one, that creates URP Lit materials instead).

I'd create a MaterialGenerator that keeps track of its materials and whenever a new material is similar (only property differences), then return the first one and provide property block overrides.

If you use a single instance of this MaterialGenerator across all Gltfast instances, this should work.

The interface would have to be adopted/extended likely.

Thanks,
Andreas

**Comment by p-skakun** [comment]
Hi, Andreas

It seems like there is no convenient way to override IMaterialGenerator in GltFast script. Is there a good reason not to add it as the constructor parameter(like for download provider and defer agent)? 
If no, could you extend the GltFast constructor and GltfAssetBase.Load method in the next release, please? Or I could submit an appropriate pull request if this works for you.

**Comment by atteneder** [comment]
> Hi, Andreas
> 
> It seems like there is no convenient way to override IMaterialGenerator in GltFast script. Is there a good reason not to add it as the constructor parameter(like for download provider and defer agent)?
> If no, could you extend the GltFast constructor and GltfAssetBase.Load method in the next release, please? Or I could submit an appropriate pull request if this works for you.

Hi @p-skakun !
I created the IMaterialGenerator abstraction with other shaders (esp. URP and HDRP) in mind, but didn't get that far as of now. But it definitely needs to be exposed!

A PR would be highly appreciated, otherwise I'll eventually implement this down the road in fall.

**Comment by atteneder** [comment]
Hi @p-skakun ,

did you manage to write your own material generator that does use MaterialPropertyBlocks? Would you share your changes?
