### ISSUE TITLE
Draco Package not found in Unity Editor

### ISSUE THREAD

**Issue by seandillon92** [atteneder/glTFast#669]
When trying to export a scene in Unity Editor using the Draco compression option, I am getting the following errors:
```
PackageMissing:KHR_draco_mesh_compression
PackageMissing:DracoUnity
```

I have installed the DracoUnity package using the .unitypackage mentioned [here](https://github.com/atteneder/DracoUnity?tab=readme-ov-file#installing).

 - glTFast version: 6.1.0
 - Unity Draco version: 4.1.0
 - Unity Editor version: 2022.3.12.f1
 - Pipeline: BiRP
 - Platform: Editor.

**Comment by atteneder** [comment]
@seandillon92 Thanks for reporting.

That's odd, you seem to have done everything right.

You could post your `Packages/manifest.json` here for further investigation.

Or, you update glTFast to [6.2.0](https://github.com/atteneder/glTFast/releases/tag/com.atteneder.gltfast%2F6.2.0). The key change is that it relies on the successor package [Draco for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.draco@5.0/manual/index.html) instead of DracoUnity (com.atteneder.draco). Maybe that'll remove your problems and you'll get an improved Draco package as a bonus.

hth

**Comment by seandillon92** [comment]
@atteneder updating to 6.2.0 fixed the issue, thanks!
