### ISSUE TITLE
Normal map should be loaded as linear not sRGB

### ISSUE THREAD

**Issue by wangvnn** [atteneder/glTFast#67]
For reference:
https://forum.unity.com/threads/get-external-normal-map-at-runtime.532892/

**Comment by atteneder** [comment]
Hi wangvnn,
thanks for the finding. I'll look into it, this week probably.

**Comment by atteneder** [comment]
Do you happen to use linear color space in your project? Because I use gamma space in my test project and it seems be correct here.

Otherwise, please provide your specs (Unity version, platform, project's color space) and sample files and explain what you'd expect (also visually) and where glTFast differs? Did you test Jpeg/PNG or KTX2/BasisU textures?

Thanks!

**Comment by atteneder** [comment]
Is fixed in master for PNG/Jpeg textures.
KTX2 still has to get fixed.

**Comment by atteneder** [comment]
Fixed in 1.0.1
