### ISSUE TITLE
Emission doesn't seem to work in URP with glTF-PBR shaders

### ISSUE THREAD

**Issue by cgcsw02** [atteneder/glTFast#684]
Emission doesn't seem to work in URP with glTF-PBR shaders. I want to describe how emission doesn't seem to function correctly in URP Unity:

Download Unity 2022.
Download glTFast.
Create a cube or any primitive shape in the scene.
Create a material and select the Shader (Shader Graphs/glTF-PBRMetallicRoughness).
Assign the material to the cube and change the Emissive color.
You will see no change in the cube.

![Screenshot 2024-03-13 145733](https://github.com/atteneder/glTFast/assets/77212963/1d4bd4ad-a3a2-4544-847f-ef446c515010)

**Comment by atteneder** [comment]
Hi,

Thanks for reporting.

While this behavior is arguably unexpected from an UX perspective, it makes sense technically. Emission can be enabled by adding the shader keyword `_EMISSIVE`.

This is not done automatically, but you can achieve it by setting the Inspector to Debug mode and adding `_EMISSIVE` to the *Valid Keywords* (as you type it gets moved to *Invalid Keywords*, but as you complete it correctly, it gets moved back to *Valid Keywords* 🤷 ).

Two thoughts:

1. This could be made much smoother by creating a custom Editor for the glTF shaders that automatically enables/disables shader keywords based on settings (See #460).
2. The shader variant explosion that stems from the use of shader keywords is problematic in itself, that's why I'm contemplating creating a single variant shader (see #703). This one wouldn't suffer that problem.

hth
