### ISSUE TITLE
Change alpha of gltf model

### ISSUE THREAD

**Issue by Merichbier** [atteneder/glTFast#72]
Hi,

I tried to play with the shader used to display the GLTF object but I wasn't able to make it transparent.
I tried to change both Color parameters with alpha channel set to 0

Do you know a way how we could make the transparency of the model controllable ?

Cheers

**Comment by atteneder** [comment]
Hi,

what is your use-caes? why do you want to set it manually?

The shader can be made transparent by setting certain shader keywords and adjusting the blending parameters (I haven't memorized them; look at DefaultMaterialGenerator.cs)

Unity's Standard shader works exactly the same, but there you have a custom Inspector, which takes care of the stuff underneath for you. Since I thought no one is going to tweak the materials manually, I haven't invested in a custom inspector.

hth

**Comment by Merichbier** [comment]
Hi @atteneder ,

Thanks again for your quick feedback !
The use case is that we load CAD models converted to GLTF and want to be able to show the different layers.
Examples with a motor, we would like to be able to set the outer case semi transparent as to better see the inner parts.

I'll check those shader, I just didn't knew where to look for them. Thanks for the hints ! I'll maybe take the chance to create a pull request if I find a clean way to do this :)

Thanks for all the great work you have done on this plugin I and my team really like it !

**Comment by atteneder** [comment]
Take a look at this:
https://github.com/atteneder/glTFast/blob/e31ea599987621337f1a98a4198a7865907d985f/Runtime/Scripts/StandardShaderHelper.cs#L72

You might prefer the "Fade" Transparency mode for your use-case. For that you need an similar, but adjusted function.

**Comment by Merichbier** [comment]
Good point I'll investiguate that thanks !

**Comment by atteneder** [comment]
Fixed via #89
