### ISSUE TITLE
There is an issue with colors not being restored correctly when using Unity GLTFast version 6.8.0.

### ISSUE THREAD

**Issue by Miyasaka-prono82** [atteneder/glTFast#721]
**Describe the bug**
There is an issue with colors not being restored correctly when using Unity GLTFast version 6.8.0.

**Files**
[Cube.zip](https://github.com/user-attachments/files/17173521/Cube.zip)

**To Reproduce**

1. Load the attached GLB file at runtime.
2. When importing the attached GLB file into Blender, the material's RGB values are (0.424, 0.220, 0.604).
3. When opening the GLB file in a text editor, the material is described as follows:
```
"materials": [
    {
        "pbrMetallicRoughness": {
            "baseColorFactor": [
                0.42352941632270815,
                0.21960784494876862,
                0.6039215922355652,
                1.0
            ],
            "metallicFactor": 0.0
        },
        "doubleSided": true
    }
],
```

However, when importing with GLTFast, the resulting RGB is (0.6825, 0.5059, 0.800).

The color changes upon importing with GLTFast. I heard this issue was fixed in version 6.7.0, but the problem still seems to persist. Is there something else I need to configure, or is the issue still present in this version?

![スクリーンショット 2024-08-29 165658](https://github.com/user-attachments/assets/71ef6dd1-b620-4c9b-8a97-bfaff41a9662)
[Blender RGB]
![スクリーンショット 2024-09-28 160211](https://github.com/user-attachments/assets/26f74b63-d5d7-444a-966a-58beef3a9874)
[Unity RGB]

**Desktop**
 - glTFast version [6.8.0]
![スクリーンショット 2024-09-28 145934](https://github.com/user-attachments/assets/568a632e-649e-4af5-88bb-00377566696f)
 - Unity Editor version [2022.3.16f1]
 - Platform: [Unity Editor]

**Comment by atteneder** [comment]
Hi @Miyasaka-prono82 ,

The difference in the actual color factor values is expected, as the values are converted from linear color space into gamma color space.

Look what happens when I take your screenshots above, sample the color from the Blender color and draw it across down to the Unity color:

![image](https://github.com/user-attachments/assets/4e56e7b0-337b-4264-8463-fb01ae3b2ec5)

They're the same color!

I'm closing this now.

If I missed something and you're able to describe or show (visually) where the discrepancy in perceived color causes issues, please re-open it.

Thanks
