### ISSUE TITLE
Modify material from opaque to transparent at runtime in URP

### ISSUE THREAD

**Issue by massimilianogaio** [atteneder/glTFast#723]
Hello, I'm encountering issues when trying to modify the transparency of materials at runtime for a GLB model. I'm using the Universal Render Pipeline in Unity 2021.3.33f1.
The starting material is this:
![image](https://github.com/user-attachments/assets/0c41eeee-45dc-43cd-b27a-81b86a04fad3)

The code I'm using is this:
```
public void SetAlphaModeBlend(UnityEngine.Material material)
{
    material.SetFloat("_Surface", 1);

    material.SetOverrideTag("RenderType", "Transparent");
    material.SetInt(srcBlendPropId, (int)UnityEngine.Rendering.BlendMode.SrcAlpha);//5
    material.SetInt(dstBlendPropId, (int)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);//10
    material.SetInt(zWritePropId, 1);
    material.DisableKeyword("_ALPHATEST_ON");
    material.EnableKeyword("_ALPHABLEND_ON");
    material.DisableKeyword("_ALPHAPREMULTIPLY_ON");
    material.renderQueue = (int)UnityEngine.Rendering.RenderQueue.Transparent;  //3000
}
```
The resulting material is this, but the alpha value of the color doesn't get updated until I manually change any material value directly from the inspector in the editor."
![image](https://github.com/user-attachments/assets/0cfc7afa-f371-490f-9cb4-87df4190cf47)

Can anyone advise me on the correct approach to use? Thank you!

PS: I read this issue but it seems to me that this is not URP releated: https://github.com/atteneder/glTFast/issues/72

**Comment by atteneder** [comment]
Hi,

apparently you've missed some required change that the inspector does as soon as you touch something.

Since glTFast's shader graphs are no speciality, so searching for tweaking Lit shader graphs at runtime in general should help.

Here's some [reference code](https://github.com/atteneder/glTFast/blob/bf011881ec4afb0e073fb241a2f18eb6edacfe7f/Runtime/Scripts/Material/UniveralRPMaterialGenerator.cs#L54) how the materials are tweaked.

Whenever I encounter such problems, I save the material (as asset) before and after the changes the inspector performs and run a diff on the asset files. This usually reveals the property/keyword I forgot to set poperly.

hth

**Comment by massimilianogaio** [comment]
Thank you very much. 
Turns out that I was missing the `material.EnableKeyword(SurfaceTypeTransparentKeyword);` directive. The trick to save the material as an asset is really smart.
