### ISSUE TITLE
Morph Target / Sparse Accessors support

### ISSUE THREAD

**Issue by atteneder** [atteneder/glTFast#8]
Follow the progress of the [morph branch](https://github.com/atteneder/glTFast/tree/morph)

- [x] Proper Disposal
- [x] Target names (from extras)
- [x] Sparse accessors
- [x] Works with Draco
- [x] Animation
  - [x] Multi primitives in separate objects

**Comment by push-pop** [comment]
Hi just wondering if there has been any movement on this, or what it would take to implement? I'm working on a project right now and trying to implement your library but got a bit stopped in my tracks because we are using blendshapes.

Happy to help/contribute if I can! We need this feature at least with our current setup. 
-n

**Comment by atteneder** [comment]
Hi @push-pop ,

Thanks for your interest!

What's probably missing from your list is retrieving the actual sparse accessor's data.

Also, I haven't looked into how the Unity Mesh API is used to create blend shapes. I'll try to read it up this week.

**Comment by push-pop** [comment]
Hi @atteneder just wondering if you had a chance to look at this stuff yet. 

I forked the repo and I am starting to dig in but I am having a hard time 
wrapping my head around the code for loading data

So I see that morph targets are in an array on each primitive. I made a new type which deserializes the accessor index for each morph attribute. (Position, Normal)

![image](https://user-images.githubusercontent.com/2680713/123884641-504fa380-d911-11eb-9ccc-38346fe2dde1.png)

So I think we need to load that data eventually into PrimitiveCreateContext since that's where the mesh actually gets created. When we have this data, we can call

`mesh.AddBlendShapeFrame( ... )` with the proper verts, normals, and tangents.

The thing I'm having a little trouble wrapping my head around is how to load that data from the accessors and get it into the PrimitiveCreateContext. 

I have been looking at VertexConfigBuffer since it seems like those are pulling data directly from the Accessor. So I wonder if I should add Targets to ScheduleVertexJobs() or if this should go somewhere different?

Sorry if that is all over the place. Any guidance is appreciated. Trying to figure out how best to do this while also learning about gltf and blendshapes at the same time :)

**Comment by atteneder** [comment]
@push-pop I have to say you seem to be on a good way!

I'm looking at this myself now and admitted, it's not super straight forward :)
glTFast has a couple of designs in place that aim to prevent duplication of data (like clustering similar mesh primitives). This adds additional layers of abstraction which are quite an obstacle for newbies to this code-base. I'm currently trying to figure out the best way to include this and I'll keep you posted.

**Comment by push-pop** [comment]
Thank you!

Yes I think I might have hit the limit of what I can do without asking a million questions. Really hoping to switch over to this library as it seems much cleaner and more extensible than the Khronos one. Plus already using your Basis lib. Unfortunately this is the one feature missing that we absolutely need. Do let me know if I can be of any assistance :)

**Comment by atteneder** [comment]
Good news, a first simple morph targets prototype is working!
See first (edited) post for details
