### ISSUE TITLE
unity 2018.2.21 import package errors

### ISSUE THREAD

**Issue by pampanelson** [atteneder/glTFast#83]
An error occurred while resolving packages:
  Project has invalid dependencies:
    com.atteneder.draco: Version is invalid.  Expected a pattern like 'x.x.x[-prerelease]', got 'https://gitlab.com/atteneder/DracoUnity.git' instead.
    com.atteneder.gltfast: Version is invalid.  Expected a pattern like 'x.x.x[-prerelease]', got 'https://github.com/atteneder/glTFast.git' instead.

here is the manifest.json

{
  "dependencies": {
    "com.atteneder.draco": "https://gitlab.com/atteneder/DracoUnity.git",
    "com.atteneder.gltfast": "https://github.com/atteneder/glTFast.git",
    "com.unity.ads": "2.0.8",
    "com.unity.analytics": "2.0.16",
    "com.unity.package-manager-ui": "1.9.11",
    "com.unity.purchasing": "2.0.3",
    "com.unity.textmeshpro": "1.2.4",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}

**Comment by atteneder** [comment]
Thanks for reporting!

Note: Since releasing version glTFast 2.0.0 a few days ago the minimum required Unity version is 2019.3! If you want to use an older version of Unity (up until 2018.2), use the branch [`gltfast-1`](https://github.com/atteneder/glTFast/tree/gltfast-1)

I reproduced it successfully and this is a Unity Bug. Upgrading to 2018.4 resolves the issue! You have to use the [`gltfast-1`](https://github.com/atteneder/glTFast/tree/gltfast-1) branch like so:

```
"com.atteneder.gltfast": "https://github.com/atteneder/glTFast.git#gltfast-1"
```

If you cannot upgrade to 2018.4 or newer, a workaround is to clone the projects into a local folder and add this folders into the `manifest.json` URL with the `file://` prefix ( See [documentation](https://docs.unity3d.com/Manual/upm-localpath.html) )

hth,
Andi
