### ISSUE TITLE
script files are not imported into Unity 2019.4.12f

### ISSUE THREAD

**Issue by zkyf** [atteneder/glTFast#93]
I downloaded the package and imported it to the project by double clicking the `.unitypackage` file, but there was nothing added to the project. The editor also tells me there is no script related to "gltf".
![image](https://user-images.githubusercontent.com/13307442/97173938-4c8cdf80-17cc-11eb-995c-57dafc8b2455.png)

**Comment by atteneder** [comment]
Hi @zkyf,

Thanks for reporting. Let's find out where it went off the rails for you.

It's normal that there was nothing added to the Assets folder, since the installer package removes itself after installation. What it does add is a scoped registry and the glTF package (see Project view under `Packages`).

Step by step:

1. Opening the installe gives you this import dialog:

<img width="462" alt="01_import" src="https://user-images.githubusercontent.com/2593014/97181311-6bbf4900-179b-11eb-88b5-8876b7fb7d14.png">

Press "Import" here

2. After import you get this notification

<img width="532" alt="02_registry" src="https://user-images.githubusercontent.com/2593014/97181381-81347300-179b-11eb-8c8e-2ff4d56c56ce.png">

You can press "Close" here.

3. If you open the *Project Settings* and go to *Package Manager* you should see an entry named `OpenUPM` with the scope `com.atteneder`

<img width="838" alt="03_UPM_settings" src="https://user-images.githubusercontent.com/2593014/97181577-ba6ce300-179b-11eb-8eb0-f3368982b6d5.png">

4. Lastly, if you open up the *Package Manager* and switch to `My registries`, you should a list also containg *glTFast* and it should be installed:

<img width="746" alt="04_UPM_list" src="https://user-images.githubusercontent.com/2593014/97181700-dcfefc00-179b-11eb-8a04-d64d351515b1.png">

> Note: glTFast is not installed in this screenshot, but you get the idea.

I hope that helps. If not, let me know where it differs for you.

**Comment by zkyf** [comment]
![image](https://user-images.githubusercontent.com/13307442/97249820-94991a00-183f-11eb-89e1-e091fdb07023.png)
![image](https://user-images.githubusercontent.com/13307442/97249829-9bc02800-183f-11eb-89f6-164b5dd50cea.png)
Thanks for reply! I have checked project setting and package manager and found they are here as your screenshots show. But still they seem dont exist in my project. I have tried remove the package from package manager and reinstall but it doesn't resolve the problem.

**Comment by zkyf** [comment]
I switched back to legacy RP and the package works when I use it as a component for a gameobject. However when i use it in scripts with `using GLTFast`, Unity says it cannot find `GLTFast`.
![image](https://user-images.githubusercontent.com/13307442/97253767-f3629180-1847-11eb-9381-fab7f248d980.png)

**Comment by atteneder** [comment]
HDRP is not supported at the moment. Still, you should be able to import glTFs (but they would end up having materials with non-working shaders). HDRP/URP support is on the TODO list though.

Do you use Assembly Definitions? Have you referenced glTFast as dependency?

**Comment by zkyf** [comment]
finally got this work! really thanks! 😄
